import { Extension } from "@tiptap/core";
import { PluginKey } from "@tiptap/pm/state";
import Suggestion, { type SuggestionOptions } from "@tiptap/suggestion";

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

const EMOJIS: EmojiItem[] = [
  // — Smileys & Emotion —
  { emoji: "😀", name: "grinning face", keywords: ["smile", "happy"] },
  { emoji: "😃", name: "grinning face with big eyes", keywords: ["smile", "happy"] },
  { emoji: "😄", name: "grinning face with smiling eyes", keywords: ["smile", "happy", "joy"] },
  { emoji: "😁", name: "beaming face", keywords: ["smile", "grin"] },
  { emoji: "😆", name: "grinning squinting face", keywords: ["laugh", "happy"] },
  { emoji: "😅", name: "grinning face with sweat", keywords: ["laugh", "nervous"] },
  { emoji: "🤣", name: "rolling on the floor laughing", keywords: ["laugh", "lol", "rofl"] },
  { emoji: "😂", name: "face with tears of joy", keywords: ["laugh", "cry", "happy"] },
  { emoji: "🙂", name: "slightly smiling face", keywords: ["smile"] },
  { emoji: "🙃", name: "upside-down face", keywords: ["silly", "sarcasm"] },
  { emoji: "😉", name: "winking face", keywords: ["wink"] },
  { emoji: "😊", name: "smiling face with smiling eyes", keywords: ["smile", "blush", "happy"] },
  { emoji: "😇", name: "smiling face with halo", keywords: ["angel", "innocent"] },
  { emoji: "🥰", name: "smiling face with hearts", keywords: ["love", "adore"] },
  { emoji: "😍", name: "heart eyes", keywords: ["love", "crush"] },
  { emoji: "🤩", name: "star-struck", keywords: ["wow", "star", "eyes"] },
  { emoji: "😘", name: "face blowing a kiss", keywords: ["kiss", "love"] },
  { emoji: "😗", name: "kissing face", keywords: ["kiss"] },
  { emoji: "😚", name: "kissing face with closed eyes", keywords: ["kiss"] },
  { emoji: "😙", name: "kissing face with smiling eyes", keywords: ["kiss"] },
  { emoji: "🥲", name: "smiling face with tear", keywords: ["sad", "smile", "grateful"] },
  { emoji: "😋", name: "face savoring food", keywords: ["yummy", "delicious", "tongue"] },
  { emoji: "😛", name: "face with tongue", keywords: ["tongue", "playful"] },
  { emoji: "😜", name: "winking face with tongue", keywords: ["tongue", "wink", "playful"] },
  { emoji: "🤪", name: "zany face", keywords: ["crazy", "silly"] },
  { emoji: "😝", name: "squinting face with tongue", keywords: ["tongue", "playful"] },
  { emoji: "🤑", name: "money-mouth face", keywords: ["money", "rich"] },
  { emoji: "🤗", name: "hugging face", keywords: ["hug", "warm"] },
  { emoji: "🤭", name: "face with hand over mouth", keywords: ["oops", "giggle"] },
  { emoji: "🤫", name: "shushing face", keywords: ["quiet", "secret", "shh"] },
  { emoji: "🤔", name: "thinking face", keywords: ["think", "hmm"] },
  { emoji: "🤐", name: "zipper-mouth face", keywords: ["quiet", "secret", "zip"] },
  { emoji: "🤨", name: "face with raised eyebrow", keywords: ["skeptical", "doubt"] },
  { emoji: "😐", name: "neutral face", keywords: ["meh", "blank"] },
  { emoji: "😑", name: "expressionless face", keywords: ["blank", "meh"] },
  { emoji: "😶", name: "face without mouth", keywords: ["silent", "mute"] },
  { emoji: "😏", name: "smirking face", keywords: ["smirk", "flirt"] },
  { emoji: "😒", name: "unamused face", keywords: ["bored", "meh"] },
  { emoji: "🙄", name: "face with rolling eyes", keywords: ["eyeroll", "annoyed"] },
  { emoji: "😬", name: "grimacing face", keywords: ["awkward", "nervous"] },
  { emoji: "🤥", name: "lying face", keywords: ["lie", "pinocchio"] },
  { emoji: "😌", name: "relieved face", keywords: ["relief", "calm"] },
  { emoji: "😔", name: "pensive face", keywords: ["sad", "thoughtful"] },
  { emoji: "😪", name: "sleepy face", keywords: ["tired", "sleep"] },
  { emoji: "🤤", name: "drooling face", keywords: ["drool", "hungry"] },
  { emoji: "😴", name: "sleeping face", keywords: ["sleep", "zzz"] },
  { emoji: "😷", name: "face with medical mask", keywords: ["sick", "mask"] },
  { emoji: "🤒", name: "face with thermometer", keywords: ["sick", "fever"] },
  { emoji: "🤕", name: "face with head-bandage", keywords: ["hurt", "injury"] },
  { emoji: "🤢", name: "nauseated face", keywords: ["sick", "vomit", "gross"] },
  { emoji: "🤮", name: "face vomiting", keywords: ["sick", "vomit", "gross"] },
  { emoji: "🥵", name: "hot face", keywords: ["hot", "sweat"] },
  { emoji: "🥶", name: "cold face", keywords: ["cold", "freeze"] },
  { emoji: "🥴", name: "woozy face", keywords: ["dizzy", "drunk"] },
  { emoji: "😵", name: "face with crossed-out eyes", keywords: ["dizzy", "dead"] },
  { emoji: "🤯", name: "exploding head", keywords: ["mind blown", "shock"] },
  { emoji: "🤠", name: "cowboy hat face", keywords: ["cowboy", "yeehaw"] },
  { emoji: "🥳", name: "partying face", keywords: ["party", "celebrate"] },
  { emoji: "🥸", name: "disguised face", keywords: ["disguise", "glasses"] },
  { emoji: "😎", name: "smiling face with sunglasses", keywords: ["cool", "sunglasses"] },
  { emoji: "🤓", name: "nerd face", keywords: ["nerd", "geek", "glasses"] },
  { emoji: "🧐", name: "face with monocle", keywords: ["classy", "inspect"] },
  { emoji: "😕", name: "confused face", keywords: ["confused", "puzzled"] },
  { emoji: "😟", name: "worried face", keywords: ["worried", "concern"] },
  { emoji: "🙁", name: "slightly frowning face", keywords: ["sad", "frown"] },
  { emoji: "😮", name: "face with open mouth", keywords: ["surprise", "shock"] },
  { emoji: "😯", name: "hushed face", keywords: ["surprise", "quiet"] },
  { emoji: "😲", name: "astonished face", keywords: ["shock", "surprise"] },
  { emoji: "😳", name: "flushed face", keywords: ["blush", "embarrassed"] },
  { emoji: "🥺", name: "pleading face", keywords: ["puppy eyes", "please", "beg"] },
  { emoji: "😦", name: "frowning face with open mouth", keywords: ["sad", "shock"] },
  { emoji: "😧", name: "anguished face", keywords: ["pain", "shock"] },
  { emoji: "😨", name: "fearful face", keywords: ["scared", "fear"] },
  { emoji: "😰", name: "anxious face with sweat", keywords: ["nervous", "anxious"] },
  { emoji: "😥", name: "sad but relieved face", keywords: ["sad", "sweat"] },
  { emoji: "😢", name: "crying face", keywords: ["cry", "sad", "tear"] },
  { emoji: "😭", name: "loudly crying face", keywords: ["cry", "sob", "sad"] },
  { emoji: "😱", name: "face screaming in fear", keywords: ["scream", "fear", "horror"] },
  { emoji: "😖", name: "confounded face", keywords: ["frustrated", "quiver"] },
  { emoji: "😣", name: "persevering face", keywords: ["struggle", "frustrated"] },
  { emoji: "😞", name: "disappointed face", keywords: ["sad", "disappointed"] },
  { emoji: "😓", name: "downcast face with sweat", keywords: ["sad", "sweat"] },
  { emoji: "😩", name: "weary face", keywords: ["tired", "frustrated"] },
  { emoji: "😫", name: "tired face", keywords: ["tired", "exhausted"] },
  { emoji: "🥱", name: "yawning face", keywords: ["yawn", "tired", "bored"] },
  { emoji: "😤", name: "face with steam from nose", keywords: ["angry", "frustrated", "triumph"] },
  { emoji: "😡", name: "pouting face", keywords: ["angry", "rage", "mad"] },
  { emoji: "😠", name: "angry face", keywords: ["angry", "mad"] },
  { emoji: "🤬", name: "face with symbols on mouth", keywords: ["swear", "curse", "angry"] },
  { emoji: "👿", name: "angry face with horns", keywords: ["devil", "evil", "angry"] },
  { emoji: "💀", name: "skull", keywords: ["death", "dead"] },
  { emoji: "💩", name: "pile of poo", keywords: ["poop", "shit"] },
  { emoji: "🤡", name: "clown face", keywords: ["clown", "funny"] },
  { emoji: "👻", name: "ghost", keywords: ["ghost", "halloween", "spooky"] },
  { emoji: "👽", name: "alien", keywords: ["alien", "ufo", "space"] },
  { emoji: "🤖", name: "robot", keywords: ["robot", "bot", "ai"] },

  // — Gestures & People —
  { emoji: "👋", name: "waving hand", keywords: ["wave", "hello", "goodbye"] },
  { emoji: "🤚", name: "raised back of hand", keywords: ["hand", "stop"] },
  { emoji: "✋", name: "raised hand", keywords: ["hand", "stop", "high five"] },
  { emoji: "🖖", name: "vulcan salute", keywords: ["spock", "star trek"] },
  { emoji: "👌", name: "ok hand", keywords: ["ok", "perfect", "fine"] },
  { emoji: "🤌", name: "pinched fingers", keywords: ["italian", "what", "chef"] },
  { emoji: "✌️", name: "victory hand", keywords: ["peace", "victory", "two"] },
  { emoji: "🤞", name: "crossed fingers", keywords: ["luck", "hope"] },
  { emoji: "🤟", name: "love-you gesture", keywords: ["love", "sign language"] },
  { emoji: "🤘", name: "sign of the horns", keywords: ["rock", "metal"] },
  { emoji: "👍", name: "thumbs up", keywords: ["like", "approve", "yes", "good", "+1"] },
  { emoji: "👎", name: "thumbs down", keywords: ["dislike", "disapprove", "no", "bad", "-1"] },
  { emoji: "✊", name: "raised fist", keywords: ["fist", "power"] },
  { emoji: "👊", name: "oncoming fist", keywords: ["punch", "fist bump"] },
  { emoji: "👏", name: "clapping hands", keywords: ["clap", "applause", "bravo"] },
  { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "hooray", "praise"] },
  { emoji: "🤝", name: "handshake", keywords: ["deal", "agreement"] },
  { emoji: "🙏", name: "folded hands", keywords: ["pray", "please", "thanks"] },
  { emoji: "💪", name: "flexed biceps", keywords: ["strong", "muscle", "flex"] },
  { emoji: "🖕", name: "middle finger", keywords: ["finger", "rude"] },
  { emoji: "🫶", name: "heart hands", keywords: ["love", "heart", "hands"] },

  // — Hearts & Emotion Symbols —
  { emoji: "❤️", name: "red heart", keywords: ["love", "heart", "red"] },
  { emoji: "🧡", name: "orange heart", keywords: ["love", "heart", "orange"] },
  { emoji: "💛", name: "yellow heart", keywords: ["love", "heart", "yellow"] },
  { emoji: "💚", name: "green heart", keywords: ["love", "heart", "green"] },
  { emoji: "💙", name: "blue heart", keywords: ["love", "heart", "blue"] },
  { emoji: "💜", name: "purple heart", keywords: ["love", "heart", "purple"] },
  { emoji: "🖤", name: "black heart", keywords: ["love", "heart", "black"] },
  { emoji: "🤍", name: "white heart", keywords: ["love", "heart", "white"] },
  { emoji: "💔", name: "broken heart", keywords: ["heartbreak", "sad"] },
  { emoji: "💯", name: "hundred points", keywords: ["100", "perfect", "score"] },
  { emoji: "💥", name: "collision", keywords: ["boom", "explosion", "bang"] },
  { emoji: "💫", name: "dizzy", keywords: ["star", "sparkle"] },
  { emoji: "💦", name: "sweat droplets", keywords: ["water", "sweat"] },
  { emoji: "🔥", name: "fire", keywords: ["flame", "hot", "lit"] },
  { emoji: "✨", name: "sparkles", keywords: ["sparkle", "shine", "glitter", "star"] },
  { emoji: "⭐", name: "star", keywords: ["star", "favorite"] },
  { emoji: "🌟", name: "glowing star", keywords: ["star", "glow", "shine"] },

  // — Animals & Nature —
  { emoji: "🐶", name: "dog face", keywords: ["dog", "puppy", "pet"] },
  { emoji: "🐱", name: "cat face", keywords: ["cat", "kitten", "pet"] },
  { emoji: "🐭", name: "mouse face", keywords: ["mouse"] },
  { emoji: "🐹", name: "hamster", keywords: ["hamster", "pet"] },
  { emoji: "🐰", name: "rabbit face", keywords: ["rabbit", "bunny"] },
  { emoji: "🦊", name: "fox", keywords: ["fox"] },
  { emoji: "🐻", name: "bear", keywords: ["bear"] },
  { emoji: "🐼", name: "panda", keywords: ["panda", "bear"] },
  { emoji: "🐨", name: "koala", keywords: ["koala"] },
  { emoji: "🐯", name: "tiger face", keywords: ["tiger"] },
  { emoji: "🦁", name: "lion", keywords: ["lion", "king"] },
  { emoji: "🐮", name: "cow face", keywords: ["cow", "moo"] },
  { emoji: "🐷", name: "pig face", keywords: ["pig"] },
  { emoji: "🐸", name: "frog", keywords: ["frog", "toad"] },
  { emoji: "🐵", name: "monkey face", keywords: ["monkey"] },
  { emoji: "🐔", name: "chicken", keywords: ["chicken", "hen"] },
  { emoji: "🐧", name: "penguin", keywords: ["penguin"] },
  { emoji: "🐦", name: "bird", keywords: ["bird"] },
  { emoji: "🦅", name: "eagle", keywords: ["eagle", "bird"] },
  { emoji: "🦋", name: "butterfly", keywords: ["butterfly", "insect"] },
  { emoji: "🐛", name: "bug", keywords: ["bug", "insect"] },
  { emoji: "🐝", name: "honeybee", keywords: ["bee", "honey"] },
  { emoji: "🐢", name: "turtle", keywords: ["turtle", "slow"] },
  { emoji: "🐍", name: "snake", keywords: ["snake"] },
  { emoji: "🐙", name: "octopus", keywords: ["octopus"] },
  { emoji: "🦄", name: "unicorn", keywords: ["unicorn", "magic"] },
  { emoji: "🌸", name: "cherry blossom", keywords: ["flower", "blossom", "spring"] },
  { emoji: "🌹", name: "rose", keywords: ["flower", "rose", "love"] },
  { emoji: "🌻", name: "sunflower", keywords: ["flower", "sun"] },
  { emoji: "🌿", name: "herb", keywords: ["plant", "leaf", "green"] },
  { emoji: "🍀", name: "four leaf clover", keywords: ["luck", "clover"] },
  { emoji: "🌲", name: "evergreen tree", keywords: ["tree", "pine"] },
  { emoji: "🌈", name: "rainbow", keywords: ["rainbow", "color"] },

  // — Food & Drink —
  { emoji: "🍎", name: "red apple", keywords: ["apple", "fruit"] },
  { emoji: "🍐", name: "pear", keywords: ["pear", "fruit"] },
  { emoji: "🍊", name: "tangerine", keywords: ["orange", "fruit"] },
  { emoji: "🍋", name: "lemon", keywords: ["lemon", "fruit"] },
  { emoji: "🍌", name: "banana", keywords: ["banana", "fruit"] },
  { emoji: "🍉", name: "watermelon", keywords: ["watermelon", "fruit"] },
  { emoji: "🍇", name: "grapes", keywords: ["grape", "fruit"] },
  { emoji: "🍓", name: "strawberry", keywords: ["strawberry", "fruit"] },
  { emoji: "🍕", name: "pizza", keywords: ["pizza", "food"] },
  { emoji: "🍔", name: "hamburger", keywords: ["burger", "food"] },
  { emoji: "🍟", name: "french fries", keywords: ["fries", "food"] },
  { emoji: "🌮", name: "taco", keywords: ["taco", "food", "mexican"] },
  { emoji: "🍣", name: "sushi", keywords: ["sushi", "food", "japanese"] },
  { emoji: "🍦", name: "ice cream", keywords: ["ice cream", "dessert"] },
  { emoji: "🍩", name: "doughnut", keywords: ["donut", "dessert"] },
  { emoji: "🍪", name: "cookie", keywords: ["cookie", "dessert"] },
  { emoji: "🎂", name: "birthday cake", keywords: ["cake", "birthday", "celebration"] },
  { emoji: "🍰", name: "shortcake", keywords: ["cake", "dessert"] },
  { emoji: "☕", name: "hot beverage", keywords: ["coffee", "tea", "drink"] },
  { emoji: "🍺", name: "beer mug", keywords: ["beer", "drink", "alcohol"] },
  { emoji: "🍷", name: "wine glass", keywords: ["wine", "drink", "alcohol"] },
  { emoji: "🥤", name: "cup with straw", keywords: ["drink", "soda", "juice"] },

  // — Travel & Places —
  { emoji: "🚗", name: "automobile", keywords: ["car", "drive"] },
  { emoji: "🚕", name: "taxi", keywords: ["taxi", "cab"] },
  { emoji: "🚀", name: "rocket", keywords: ["rocket", "space", "launch"] },
  { emoji: "✈️", name: "airplane", keywords: ["plane", "travel", "flight"] },
  { emoji: "🚂", name: "locomotive", keywords: ["train"] },
  { emoji: "🚲", name: "bicycle", keywords: ["bike", "cycle"] },
  { emoji: "⛵", name: "sailboat", keywords: ["boat", "sail"] },
  { emoji: "🏠", name: "house", keywords: ["home", "house"] },
  { emoji: "🏢", name: "office building", keywords: ["office", "building", "work"] },
  { emoji: "🏖️", name: "beach with umbrella", keywords: ["beach", "vacation"] },
  { emoji: "⛰️", name: "mountain", keywords: ["mountain"] },
  { emoji: "🌍", name: "globe showing Europe-Africa", keywords: ["world", "earth", "globe"] },
  { emoji: "🌙", name: "crescent moon", keywords: ["moon", "night"] },
  { emoji: "☀️", name: "sun", keywords: ["sun", "sunny", "weather"] },
  { emoji: "⛈️", name: "cloud with lightning and rain", keywords: ["storm", "weather"] },
  { emoji: "❄️", name: "snowflake", keywords: ["snow", "cold", "winter"] },

  // — Objects —
  { emoji: "💻", name: "laptop", keywords: ["computer", "laptop", "code"] },
  { emoji: "📱", name: "mobile phone", keywords: ["phone", "mobile", "cell"] },
  { emoji: "⌨️", name: "keyboard", keywords: ["keyboard", "type"] },
  { emoji: "🖥️", name: "desktop computer", keywords: ["computer", "desktop", "monitor"] },
  { emoji: "📷", name: "camera", keywords: ["camera", "photo"] },
  { emoji: "🔔", name: "bell", keywords: ["bell", "notification", "alert"] },
  { emoji: "📚", name: "books", keywords: ["book", "read", "study"] },
  { emoji: "📝", name: "memo", keywords: ["note", "write", "memo"] },
  { emoji: "📎", name: "paperclip", keywords: ["clip", "attach"] },
  { emoji: "🔑", name: "key", keywords: ["key", "lock", "password"] },
  { emoji: "🔒", name: "locked", keywords: ["lock", "secure", "private"] },
  { emoji: "🔓", name: "unlocked", keywords: ["unlock", "open"] },
  { emoji: "💡", name: "light bulb", keywords: ["idea", "bulb", "light"] },
  { emoji: "🔧", name: "wrench", keywords: ["tool", "fix", "wrench"] },
  { emoji: "🔨", name: "hammer", keywords: ["tool", "hammer", "build"] },
  { emoji: "⚙️", name: "gear", keywords: ["settings", "gear", "config"] },
  { emoji: "🗑️", name: "wastebasket", keywords: ["trash", "delete", "bin"] },
  { emoji: "📦", name: "package", keywords: ["box", "package", "delivery"] },
  { emoji: "🎁", name: "wrapped gift", keywords: ["gift", "present"] },
  { emoji: "🎈", name: "balloon", keywords: ["balloon", "party"] },
  { emoji: "🎉", name: "party popper", keywords: ["party", "celebrate", "tada"] },
  { emoji: "🎊", name: "confetti ball", keywords: ["confetti", "celebrate"] },
  { emoji: "🏆", name: "trophy", keywords: ["trophy", "win", "award"] },
  { emoji: "🎯", name: "bullseye", keywords: ["target", "goal", "dart"] },
  { emoji: "🎮", name: "video game", keywords: ["game", "controller", "play"] },
  { emoji: "🎵", name: "musical note", keywords: ["music", "note", "song"] },
  { emoji: "🎶", name: "musical notes", keywords: ["music", "notes", "song"] },
  { emoji: "🎤", name: "microphone", keywords: ["mic", "sing", "karaoke"] },

  // — Symbols —
  { emoji: "✅", name: "check mark button", keywords: ["check", "done", "yes", "complete"] },
  { emoji: "❌", name: "cross mark", keywords: ["no", "wrong", "error", "delete"] },
  { emoji: "❓", name: "question mark", keywords: ["question", "help"] },
  { emoji: "❗", name: "exclamation mark", keywords: ["exclamation", "important", "alert"] },
  { emoji: "⚠️", name: "warning", keywords: ["warning", "caution", "alert"] },
  { emoji: "🚫", name: "prohibited", keywords: ["no", "forbidden", "ban"] },
  { emoji: "♻️", name: "recycling symbol", keywords: ["recycle", "green"] },
  { emoji: "➡️", name: "right arrow", keywords: ["arrow", "right", "next"] },
  { emoji: "⬅️", name: "left arrow", keywords: ["arrow", "left", "back"] },
  { emoji: "⬆️", name: "up arrow", keywords: ["arrow", "up"] },
  { emoji: "⬇️", name: "down arrow", keywords: ["arrow", "down"] },
  { emoji: "🔄", name: "counterclockwise arrows", keywords: ["refresh", "reload", "sync"] },
  { emoji: "ℹ️", name: "information", keywords: ["info", "information"] },
  { emoji: "🆕", name: "new button", keywords: ["new"] },
  { emoji: "🆗", name: "ok button", keywords: ["ok", "okay"] },
  { emoji: "🔴", name: "red circle", keywords: ["red", "circle", "dot"] },
  { emoji: "🟢", name: "green circle", keywords: ["green", "circle", "dot"] },
  { emoji: "🔵", name: "blue circle", keywords: ["blue", "circle", "dot"] },
  { emoji: "🟡", name: "yellow circle", keywords: ["yellow", "circle", "dot"] },
  { emoji: "🏳️", name: "white flag", keywords: ["flag", "surrender"] },
  { emoji: "🏴", name: "black flag", keywords: ["flag"] },
];

export function getEmojiItems({ query }: { query: string }): EmojiItem[] {
  if (!query) return EMOJIS.slice(0, 20);
  const q = query.toLowerCase();
  return EMOJIS.filter(
    (e) => e.name.includes(q) || e.keywords.some((k) => k.includes(q)),
  ).slice(0, 20);
}

export const emojiCommandPluginKey = new PluginKey("emoji-command");

const EmojiCommand = Extension.create({
  name: "emojiCommand",

  addOptions() {
    return {
      suggestion: {
        char: ":",
        command: ({ editor, range, props }: any) => {
          editor
            .chain()
            .focus()
            .deleteRange(range)
            .insertContent(props.emoji)
            .run();
        },
        allow: ({ state, range }: any) => {
          const $from = state.doc.resolve(range.from);
          if ($from.parent.type.name === "codeBlock") {
            return false;
          }
          return true;
        },
      } as Partial<SuggestionOptions>,
    };
  },

  addProseMirrorPlugins() {
    return [
      Suggestion({
        pluginKey: emojiCommandPluginKey,
        ...this.options.suggestion,
        editor: this.editor,
      }),
    ];
  },
});

export default EmojiCommand;
