import prettier from 'eslint-config-prettier';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

export default defineConfig(
	{
		// The repo's .gitignore lives one level up (this package is nested under
		// app/), so includeIgnoreFile can't anchor to it — the generated trees are
		// listed here instead. Keep in sync with ../.gitignore.
		ignores: [
			'.svelte-kit/',
			'build/',
			'static/',
			'src/lib/paraglide/',
			// Stale output from an older Paraglide outdir; unreferenced.
			'src/paraglide/',
			// Generated by Tauri Specta; regenerated by `pnpm gen:bindings`.
			'src/lib/bindings.ts',
			'src-tauri/target/',
			'src-tauri/gen/'
		]
	},
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			'no-undef': 'off',
			'no-empty': ['error', { allowEmptyCatch: true }]
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		rules: {
			// A leading underscore is this codebase's marker for "bound on purpose,
			// read nowhere" — reactive reads kept for their side effect, and
			// destructured fields skipped over. Anything else is dead code, and is
			// a warning only while the shadcn/Tailwind migration churns imports.
			'@typescript-eslint/no-unused-vars': [
				'warn',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_'
				}
			],
			// Owned by `pnpm check:invariants`, which allowlists the one file that
			// may use {@html} instead of turning the check off per call site.
			'svelte/no-at-html-tags': 'off'
		}
	},
	{
		// Standing cleanup, not accepted style. Each of these needs a real change
		// — a SvelteMap for a reactive Map, a keyed each, an actual type — so they
		// are warnings until they are paid down, then promoted back to 'error'.
		// Counts at the time of writing: see the note in the PR that added this.
		rules: {
			'svelte/prefer-svelte-reactivity': 'warn',
			'svelte/require-each-key': 'warn',
			'svelte/no-navigation-without-resolve': 'warn',
			'svelte/no-dom-manipulating': 'warn',
			'svelte/prefer-writable-derived': 'warn',
			'svelte/no-unused-svelte-ignore': 'warn',
			'@typescript-eslint/no-explicit-any': 'warn',
			'@typescript-eslint/no-unused-expressions': 'warn',
			'@typescript-eslint/no-empty-object-type': 'warn',
			'@typescript-eslint/no-this-alias': 'warn',
			'preserve-caught-error': 'warn',
			'no-useless-escape': 'warn',
			'no-useless-assignment': 'warn'
		}
	}
);
