// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	generateMnemonic: () => typedError<string, string>(__TAURI_INVOKE("generate_mnemonic")),
	deriveVaultKeys: (mnemonic: string) => typedError<VaultKeys, string>(__TAURI_INVOKE("derive_vault_keys", { mnemonic })),
	setVaultDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_vault_directory", { path })),
	listDirectory: (path: string) => typedError<FsEntry[], string>(__TAURI_INVOKE("list_directory", { path })),
	walkDirectory: (root: string, includeHidden: boolean) => typedError<FsEntry[], string>(__TAURI_INVOKE("walk_directory", { root, includeHidden })),
	buildVisibleTree: (root: string, expanded: string[], sortBy: string, hidden: string[]) => typedError<TreeEntry[], string>(__TAURI_INVOKE("build_visible_tree", { root, expanded, sortBy, hidden })),
	buildSubtree: (folder: string, depthOffset: number, expanded: string[], sortBy: string, hidden: string[]) => typedError<TreeEntry[], string>(__TAURI_INVOKE("build_subtree", { folder, depthOffset, expanded, sortBy, hidden })),
	deleteEntry: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_entry", { path })),
	trashList: (vaultPath: string) => typedError<TrashItem[], string>(__TAURI_INVOKE("trash_list", { vaultPath })),
	trashRestore: (vaultPath: string, id: string) => typedError<string, string>(__TAURI_INVOKE("trash_restore", { vaultPath, id })),
	trashDelete: (vaultPath: string, id: string) => typedError<null, string>(__TAURI_INVOKE("trash_delete", { vaultPath, id })),
	trashEmpty: (vaultPath: string) => typedError<number, string>(__TAURI_INVOKE("trash_empty", { vaultPath })),
	renameEntry: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("rename_entry", { from, to })),
	createDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_directory", { path })),
	fileExists: (path: string) => __TAURI_INVOKE<boolean>("file_exists", { path }),
	fileMetadata: (path: string) => typedError<FileMetadata, string>(__TAURI_INVOKE("file_metadata", { path })),
	copyFile: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_file", { from, to })),
	importExternalFile: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("import_external_file", { from, to })),
	importExternalDirectory: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("import_external_directory", { from, to })),
	importAttachment: (from: string, folder: string) => typedError<string, string>(__TAURI_INVOKE("import_attachment", { from, folder })),
	sweepUnusedAttachments: (folder: string) => typedError<number, string>(__TAURI_INVOKE("sweep_unused_attachments", { folder })),
	copyDirectory: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_directory", { from, to })),
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
	setMtime: (path: string, mtime: number) => typedError<null, string>(__TAURI_INVOKE("set_mtime", { path, mtime })),
	watchFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("watch_file", { path })),
	unwatchFile: () => typedError<null, string>(__TAURI_INVOKE("unwatch_file")),
	watchVault: (path: string) => typedError<null, string>(__TAURI_INVOKE("watch_vault", { path })),
	unwatchVault: () => typedError<null, string>(__TAURI_INVOKE("unwatch_vault")),
	searchFiles: (root: string, query: string) => typedError<FsEntry[], string>(__TAURI_INVOKE("search_files", { root, query })),
	replaceInFile: (path: string, search: string, replace: string, caseSensitive: boolean) => typedError<number, string>(__TAURI_INVOKE("replace_in_file", { path, search, replace, caseSensitive })),
	exportVaultZip: (vaultPath: string, destPath: string) => typedError<null, string>(__TAURI_INVOKE("export_vault_zip", { vaultPath, destPath })),
	hasUnsyncedChanges: (vaultPath: string, encryptionKey: number[]) => typedError<boolean, string>(__TAURI_INVOKE("has_unsynced_changes", { vaultPath, encryptionKey })),
	indexSearch: (root: string, query: string, limit: number) => typedError<SearchHit[], string>(__TAURI_INVOKE("index_search", { root, query, limit })),
	indexRebuild: (root: string) => typedError<number, string>(__TAURI_INVOKE("index_rebuild", { root })),
	indexTags: (root: string) => typedError<TagInfo[], string>(__TAURI_INVOKE("index_tags", { root })),
	indexBacklinks: (root: string, path: string) => typedError<Backlink[], string>(__TAURI_INVOKE("index_backlinks", { root, path })),
	llmConfigure: (config: LlmConfig) => typedError<null, string>(__TAURI_INVOKE("llm_configure", { config })),
	llmListModels: (config: LlmConfig) => typedError<string[], string>(__TAURI_INVOKE("llm_list_models", { config })),
	llmAsk: (requestId: string, question: string, onEvent: Channel<AskEvent>) => typedError<null, string>(__TAURI_INVOKE("llm_ask", { requestId, question, onEvent })),
	llmCancel: (requestId: string) => typedError<null, string>(__TAURI_INVOKE("llm_cancel", { requestId })),
	s3Configure: (config: S3Config) => typedError<null, string>(__TAURI_INVOKE("s3_configure", { config })),
	s3TestConnection: () => typedError<string, string>(__TAURI_INVOKE("s3_test_connection")),
	saveSettings: (vaultPath: string, encryptionKey: number[], settings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("save_settings", { vaultPath, encryptionKey, settings })),
	loadSettings: (vaultPath: string, encryptionKey: number[]) => typedError<{
	s3: S3Config | null,
	attachment_folder?: string | null,
	auto_sync?: boolean | null,
	conflict_strategy?: string | null,
	llm?: LlmConfig | null,
} | null, string>(__TAURI_INVOKE("load_settings", { vaultPath, encryptionKey })),
	exportSettingsString: (encryptionKey: number[], settings: AppSettings) => typedError<string, string>(__TAURI_INVOKE("export_settings_string", { encryptionKey, settings })),
	importSettingsString: (encryptionKey: number[], encoded: string) => typedError<AppSettings, string>(__TAURI_INVOKE("import_settings_string", { encryptionKey, encoded })),
	saveWorkspaceState: (vaultPath: string, encryptionKey: number[], state: WorkspaceState) => typedError<null, string>(__TAURI_INVOKE("save_workspace_state", { vaultPath, encryptionKey, state })),
	loadWorkspaceState: (vaultPath: string, encryptionKey: number[]) => typedError<{
	panes: WorkspacePane[],
	pane_flexes: (number | null)[],
	active_pane_index: number,
	expanded_folders: string[],
	sidebar_open: boolean,
	sidebar_width: number | null,
	sort_order: string,
	terminal_open?: boolean,
	terminal_height?: number | null,
} | null, string>(__TAURI_INVOKE("load_workspace_state", { vaultPath, encryptionKey })),
	saveSession: (mnemonic: string, vaultPath: string) => typedError<null, string>(__TAURI_INVOKE("save_session", { mnemonic, vaultPath })),
	loadSession: () => typedError<{
	name: string,
	mnemonic: string,
	vault_path: string,
} | null, string>(__TAURI_INVOKE("load_session")),
	clearSession: () => typedError<null, string>(__TAURI_INVOKE("clear_session")),
	loadVaultProfiles: () => typedError<VaultProfiles, string>(__TAURI_INVOKE("load_vault_profiles")),
	saveVaultProfile: (profile: VaultProfile) => typedError<null, string>(__TAURI_INVOKE("save_vault_profile", { profile })),
	deleteVaultProfile: (vaultPath: string) => typedError<null, string>(__TAURI_INVOKE("delete_vault_profile", { vaultPath })),
	saveSnapshot: (vaultPath: string, filePath: string, content: number[]) => typedError<string, string>(__TAURI_INVOKE("save_snapshot", { vaultPath, filePath, content })),
	listSnapshots: (vaultPath: string, filePath: string) => typedError<Snapshot[], string>(__TAURI_INVOKE("list_snapshots", { vaultPath, filePath })),
	readSnapshot: (vaultPath: string, filePath: string, snapshotFilename: string) => typedError<number[], string>(__TAURI_INVOKE("read_snapshot", { vaultPath, filePath, snapshotFilename })),
	deleteSnapshot: (vaultPath: string, filePath: string, snapshotFilename: string) => typedError<null, string>(__TAURI_INVOKE("delete_snapshot", { vaultPath, filePath, snapshotFilename })),
	clearSnapshots: (vaultPath: string, filePath: string) => typedError<number, string>(__TAURI_INVOKE("clear_snapshots", { vaultPath, filePath })),
	renameHistory: (vaultPath: string, oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("rename_history", { vaultPath, oldPath, newPath })),
	fuzzyFilterFiles: (files: FuzzyEntry[], query: string, limit: number) => __TAURI_INVOKE<FuzzyEntry[]>("fuzzy_filter_files", { files, query, limit }),
	hashFilesBatch: (vaultPath: string, paths: string[]) => typedError<string[], string>(__TAURI_INVOKE("hash_files_batch", { vaultPath, paths })),
	loadManifest: (vaultPath: string, encryptionKey: number[]) => typedError<Manifest_Serialize, string>(__TAURI_INVOKE("load_manifest", { vaultPath, encryptionKey })),
	saveManifest: (vaultPath: string, encryptionKey: number[], manifest: Manifest_Deserialize) => typedError<null, string>(__TAURI_INVOKE("save_manifest", { vaultPath, encryptionKey, manifest })),
	computeSyncActions: (baseFiles: ManifestEntry_Deserialize[], localFiles: ManifestEntry_Deserialize[], remoteFiles: ManifestEntry_Deserialize[]) => __TAURI_INVOKE<SyncAction[]>("compute_sync_actions", { baseFiles, localFiles, remoteFiles }),
	collectTombstones: (files: ManifestEntry_Deserialize[]) => __TAURI_INVOKE<ManifestEntry_Serialize[]>("collect_tombstones", { files }),
	mergeTombstones: (a: ManifestEntry_Deserialize[], b: ManifestEntry_Deserialize[]) => __TAURI_INVOKE<ManifestEntry_Serialize[]>("merge_tombstones", { a, b }),
	pruneTombstones: (tombstones: ManifestEntry_Deserialize[], nowSeconds: number) => __TAURI_INVOKE<ManifestEntry_Serialize[]>("prune_tombstones", { tombstones, nowSeconds }),
	syncUploadFiles: (vaultPath: string, s3Prefix: string, paths: string[], encryptionKey: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_upload_files", { vaultPath, s3Prefix, paths, encryptionKey })),
	syncDownloadFiles: (vaultPath: string, s3Prefix: string, paths: string[], mtimes: number[], encryptionKey: number[]) => typedError<string[], string>(__TAURI_INVOKE("sync_download_files", { vaultPath, s3Prefix, paths, mtimes, encryptionKey })),
	syncUploadManifest: (s3Prefix: string, encryptionKey: number[], manifest: Manifest_Deserialize) => typedError<null, string>(__TAURI_INVOKE("sync_upload_manifest", { s3Prefix, encryptionKey, manifest })),
	syncDeleteFiles: (s3Prefix: string, paths: string[], encryptionKey: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_delete_files", { s3Prefix, paths, encryptionKey })),
	pathToS3Key: (relPath: string, encryptionKey: number[]) => __TAURI_INVOKE<string>("path_to_s3_key", { relPath, encryptionKey }),
	ptySpawn: (id: number, cols: number, rows: number, onOutput: Channel<string>, onExit: Channel<number>) => typedError<null, string>(__TAURI_INVOKE("pty_spawn", { id, cols, rows, onOutput, onExit })),
	ptyWrite: (id: number, data: string) => typedError<null, string>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: number, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("pty_resize", { id, cols, rows })),
	ptyKill: (id: number) => typedError<null, string>(__TAURI_INVOKE("pty_kill", { id })),
	ptyKillAll: () => typedError<null, string>(__TAURI_INVOKE("pty_kill_all")),
};

/* Types */
export type ApiFormat = "openai" | "anthropic";

export type AppSettings = {
	s3: S3Config | null,
	attachment_folder?: string | null,
	auto_sync?: boolean | null,
	conflict_strategy?: string | null,
	llm?: LlmConfig | null,
};

export type AskEvent = { type: "tool"; name: string; summary: string } | { type: "delta"; text: string } | { type: "done" } | { type: "error"; status: number | null; message: string };

export type Backlink = {
	path: string,
	name: string,
};

export type Effort = "low" | "medium" | "high";

export type FileMetadata = {
	size: number | null,
	modified: number,
};

export type FsEntry = {
	name: string,
	is_dir: boolean,
	path: string,
	modified: number,
};

export type FuzzyEntry = {
	name: string,
	path: string,
};

export type LlmConfig = {
	api_format: ApiFormat,
	base_url?: string,
	api_key?: string,
	model: string,
	effort?: Effort | null,
};

export type Manifest = Manifest_Serialize | Manifest_Deserialize;

export type ManifestEntry = ManifestEntry_Serialize | ManifestEntry_Deserialize;

export type ManifestEntry_Deserialize = {
	path: string,
	hash: string,
	modified: number,
	deleted_at: number | null,
};

export type ManifestEntry_Serialize = {
	path: string,
	hash: string,
	modified: number,
	deleted_at?: number | null,
};

export type Manifest_Deserialize = {
	version: number,
	files: ManifestEntry_Deserialize[],
};

export type Manifest_Serialize = {
	version: number,
	files: ManifestEntry_Serialize[],
};

export type S3Config = {
	endpoint: string,
	bucket: string,
	region: string,
	access_key: string,
	secret_key: string,
};

export type SearchHit = {
	path: string,
	name: string,
	snippet: string,
};

export type Snapshot = {
	filename: string,
	timestamp: number,
	size: number,
};

export type SyncAction = {
	kind: string,
	path: string,
};

export type TagInfo = {
	tag: string,
	count: number,
	files: string[],
};

export type TrashItem = {
	id: string,
	name: string,
	path: string,
	is_dir: boolean,
	deleted_at: number | null,
	has_history: boolean,
};

export type TreeEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	modified: number,
	depth: number,
};

export type VaultKeys = {
	vault_id: string,
	encryption_key: number[],
};

export type VaultProfile = {
	name: string,
	mnemonic: string,
	vault_path: string,
};

export type VaultProfiles = {
	profiles: VaultProfile[],
	last_used: string | null,
};

export type WorkspacePane = {
	tabs: WorkspaceTab[],
	active_tab_index: number,
};

export type WorkspaceState = {
	panes: WorkspacePane[],
	pane_flexes: (number | null)[],
	active_pane_index: number,
	expanded_folders: string[],
	sidebar_open: boolean,
	sidebar_width: number | null,
	sort_order: string,
	terminal_open?: boolean,
	terminal_height?: number | null,
};

export type WorkspaceTab = {
	path: string,
	type: string,
	pinned?: boolean,
	view_mode?: string,
	cursor_pos?: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

