// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Generate a new BIP-39 12-word mnemonic (128-bit entropy). */
	generateMnemonic: () => typedError<string, string>(__TAURI_INVOKE("generate_mnemonic")),
	/**  Derive vault_id and encryption_key from a BIP-39 mnemonic. */
	deriveVaultKeys: (mnemonic: string) => typedError<VaultKeys, string>(__TAURI_INVOKE("derive_vault_keys", { mnemonic })),
	setVaultDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_vault_directory", { path })),
	listDirectory: (path: string) => typedError<FsEntry[], string>(__TAURI_INVOKE("list_directory", { path })),
	/**
	 *  Recursively walk an entire directory tree in a single call, returning all
	 *  entries (files and directories). Hidden entries (starting with `.`) are
	 *  skipped unless `include_hidden` is true.
	 */
	walkDirectory: (root: string, includeHidden: boolean) => typedError<FsEntry[], string>(__TAURI_INVOKE("walk_directory", { root, includeHidden })),
	/**
	 *  Read multiple Markdown files and extract `[[wiki-links]]` from each — all
	 *  in native Rust using a single IPC call.
	 */
	readLinkBatch: (paths: string[]) => __TAURI_INVOKE<LinkEntry[]>("read_link_batch", { paths }),
	/**
	 *  Build a flat, sorted, depth-annotated list of every currently-visible
	 *  tree row in a single native call.
	 */
	buildVisibleTree: (root: string, expanded: string[], sortBy: string) => typedError<TreeEntry[], string>(__TAURI_INVOKE("build_visible_tree", { root, expanded, sortBy })),
	/**
	 *  Build the subtree for a single folder at a given depth offset.
	 *  Used for incremental expand — avoids rebuilding the entire tree.
	 */
	buildSubtree: (folder: string, depthOffset: number, expanded: string[], sortBy: string) => typedError<TreeEntry[], string>(__TAURI_INVOKE("build_subtree", { folder, depthOffset, expanded, sortBy })),
	deleteEntry: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_entry", { path })),
	renameEntry: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("rename_entry", { from, to })),
	createDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_directory", { path })),
	fileExists: (path: string) => __TAURI_INVOKE<boolean>("file_exists", { path }),
	copyFile: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_file", { from, to })),
	copyDirectory: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_directory", { from, to })),
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
	/**
	 *  Set the modification time of a file to a specific unix timestamp (seconds).
	 * 
	 *  `mtime` is a u32 (unix seconds) because specta forbids exporting u64 across
	 *  the IPC boundary. Unix-second timestamps fit in u32 until 2106; the value is
	 *  widened to i64 for `filetime` below.
	 */
	setMtime: (path: string, mtime: number) => typedError<null, string>(__TAURI_INVOKE("set_mtime", { path, mtime })),
	watchFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("watch_file", { path })),
	unwatchFile: () => typedError<null, string>(__TAURI_INVOKE("unwatch_file")),
	/**
	 *  Watch the entire vault directory recursively. Emits `"vault-fs-changed"`
	 *  immediately whenever a non-hidden file is created, modified or deleted.
	 */
	watchVault: (path: string) => typedError<null, string>(__TAURI_INVOKE("watch_vault", { path })),
	unwatchVault: () => typedError<null, string>(__TAURI_INVOKE("unwatch_vault")),
	searchFiles: (root: string, query: string) => typedError<FsEntry[], string>(__TAURI_INVOKE("search_files", { root, query })),
	searchFileContents: (root: string, query: string, caseSensitive: boolean) => typedError<ContentMatch[], string>(__TAURI_INVOKE("search_file_contents", { root, query, caseSensitive })),
	replaceInFile: (path: string, search: string, replace: string, caseSensitive: boolean) => typedError<number, string>(__TAURI_INVOKE("replace_in_file", { path, search, replace, caseSensitive })),
	/**  Scan all `.md` files under `root` and collect unique `#tag` tokens. */
	listAllTags: (root: string) => typedError<TagInfo[], string>(__TAURI_INVOKE("list_all_tags", { root })),
	exportVaultZip: (vaultPath: string, destPath: string) => typedError<null, string>(__TAURI_INVOKE("export_vault_zip", { vaultPath, destPath })),
	/**
	 *  Check whether the vault has local changes compared to the last-synced
	 *  base manifest.
	 * 
	 *  Caches the result for up to 2 seconds to avoid repeated full vault walks
	 *  when called in quick succession (e.g. on every vault-fs-changed event).
	 */
	hasUnsyncedChanges: (vaultPath: string, encryptionKey: number[]) => typedError<boolean, string>(__TAURI_INVOKE("has_unsynced_changes", { vaultPath, encryptionKey })),
	s3Configure: (config: S3Config) => typedError<null, string>(__TAURI_INVOKE("s3_configure", { config })),
	s3GetConfig: () => typedError<{
	endpoint: string,
	bucket: string,
	region: string,
	access_key: string,
	secret_key: string,
} | null, string>(__TAURI_INVOKE("s3_get_config")),
	s3TestConnection: () => typedError<string, string>(__TAURI_INVOKE("s3_test_connection")),
	s3List: (prefix: string) => typedError<string[], string>(__TAURI_INVOKE("s3_list", { prefix })),
	s3Delete: (key: string) => typedError<null, string>(__TAURI_INVOKE("s3_delete", { key })),
	/**  Save settings encrypted to disk at {vault_path}/.margin/settings.enc */
	saveSettings: (vaultPath: string, encryptionKey: number[], settings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("save_settings", { vaultPath, encryptionKey, settings })),
	/**  Load settings from disk and decrypt */
	loadSettings: (vaultPath: string, encryptionKey: number[]) => typedError<{
	s3: S3Config | null,
	attachment_folder?: string | null,
	auto_sync?: boolean | null,
	conflict_strategy?: string | null,
} | null, string>(__TAURI_INVOKE("load_settings", { vaultPath, encryptionKey })),
	/**  Export all settings as an encrypted base64 string (portable) */
	exportSettingsString: (encryptionKey: number[], settings: AppSettings) => typedError<string, string>(__TAURI_INVOKE("export_settings_string", { encryptionKey, settings })),
	/**  Import settings from an encrypted base64 string */
	importSettingsString: (encryptionKey: number[], encoded: string) => typedError<AppSettings, string>(__TAURI_INVOKE("import_settings_string", { encryptionKey, encoded })),
	/**  Save workspace state encrypted to disk at {vault_path}/.margin/workspace.enc */
	saveWorkspaceState: (vaultPath: string, encryptionKey: number[], state: WorkspaceState) => typedError<null, string>(__TAURI_INVOKE("save_workspace_state", { vaultPath, encryptionKey, state })),
	/**  Load workspace state from disk and decrypt */
	loadWorkspaceState: (vaultPath: string, encryptionKey: number[]) => typedError<{
	panes: WorkspacePane[],
	pane_flexes: (number | null)[],
	active_pane_index: number,
	expanded_folders: string[],
	sidebar_open: boolean,
	sidebar_width: number | null,
	sidebar_view: string,
	sort_order: string,
} | null, string>(__TAURI_INVOKE("load_workspace_state", { vaultPath, encryptionKey })),
	/**  Legacy compatibility: save_session now saves/updates a profile */
	saveSession: (mnemonic: string, vaultPath: string) => typedError<null, string>(__TAURI_INVOKE("save_session", { mnemonic, vaultPath })),
	/**  Legacy compatibility: load_session returns the last-used profile */
	loadSession: () => typedError<{
	name: string,
	mnemonic: string,
	vault_path: string,
} | null, string>(__TAURI_INVOKE("load_session")),
	/**  Legacy compatibility: clear_session removes the last-used flag but keeps profiles */
	clearSession: () => typedError<null, string>(__TAURI_INVOKE("clear_session")),
	/**  Load all saved vault profiles */
	loadVaultProfiles: () => typedError<VaultProfiles, string>(__TAURI_INVOKE("load_vault_profiles")),
	/**  Save or update a vault profile. If a profile with the same vault_path exists, update it. */
	saveVaultProfile: (profile: VaultProfile) => typedError<null, string>(__TAURI_INVOKE("save_vault_profile", { profile })),
	/**  Delete a vault profile by vault_path */
	deleteVaultProfile: (vaultPath: string) => typedError<null, string>(__TAURI_INVOKE("delete_vault_profile", { vaultPath })),
	/**
	 *  Save a snapshot of the given file content.
	 *  The snapshot is stored as `<timestamp>.md` inside the history directory.
	 *  If the number of snapshots exceeds the limit, the oldest are pruned.
	 */
	saveSnapshot: (vaultPath: string, filePath: string, content: number[]) => typedError<string, string>(__TAURI_INVOKE("save_snapshot", { vaultPath, filePath, content })),
	/**  List all snapshots for a given file, sorted newest-first. */
	listSnapshots: (vaultPath: string, filePath: string) => typedError<Snapshot[], string>(__TAURI_INVOKE("list_snapshots", { vaultPath, filePath })),
	/**  Read the content of a specific snapshot. */
	readSnapshot: (vaultPath: string, filePath: string, snapshotFilename: string) => typedError<number[], string>(__TAURI_INVOKE("read_snapshot", { vaultPath, filePath, snapshotFilename })),
	/**  Delete a specific snapshot. */
	deleteSnapshot: (vaultPath: string, filePath: string, snapshotFilename: string) => typedError<null, string>(__TAURI_INVOKE("delete_snapshot", { vaultPath, filePath, snapshotFilename })),
	/**
	 *  Delete all snapshots for a given file. Returns the number of snapshots
	 *  deleted as a u32 (not u64) so specta can export it; the count is bounded by
	 *  `MAX_SNAPSHOTS_PER_FILE` and never approaches u32::MAX.
	 */
	clearSnapshots: (vaultPath: string, filePath: string) => typedError<number, string>(__TAURI_INVOKE("clear_snapshots", { vaultPath, filePath })),
	/**
	 *  Delete the entire history subtree for a given path (file or directory).
	 *  When a directory is deleted, all history for every file beneath it is removed.
	 */
	clearHistoryTree: (vaultPath: string, entryPath: string) => typedError<null, string>(__TAURI_INVOKE("clear_history_tree", { vaultPath, entryPath })),
	/**  Move/rename the history directory when a file or directory is renamed. */
	renameHistory: (vaultPath: string, oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("rename_history", { vaultPath, oldPath, newPath })),
	/**
	 *  Fast substring search on a flattened ProseMirror document.
	 * 
	 *  `text`        – the concatenated text content of every text node.
	 *  `pm_offsets`  – parallel array: pm_offsets[i] is the ProseMirror position of text[i].
	 *  `gaps`        – sorted indices into `text` where a block boundary exists
	 *                  (i.e. pm_offsets[i] != pm_offsets[i-1] + 1). Matches that
	 *                  span a gap are rejected.
	 *  `needle`      – the search term.
	 *  `case_sensitive` – whether to compare case-sensitively.
	 * 
	 *  Returns `(from, to)` pairs in ProseMirror position space.
	 */
	searchInText: (text: string, pmOffsets: number[], gaps: number[], needle: string, caseSensitive: boolean) => __TAURI_INVOKE<TextMatch[]>("search_in_text", { text, pmOffsets, gaps, needle, caseSensitive }),
	/**
	 *  Extract `[[title]]` wiki-links from a batch of ProseMirror text nodes.
	 * 
	 *  Each `TextNode` carries the node's text content and its ProseMirror start
	 *  position. Returns `(from, to, title)` triples in PM position space.
	 * 
	 *  This replaces the per-node regex scan in JS — a single IPC call handles
	 *  all text nodes at once.
	 */
	extractWikiLinks: (nodes: TextNode[]) => __TAURI_INVOKE<WikiLinkMatch[]>("extract_wiki_links", { nodes }),
	fuzzyFilterFiles: (files: FuzzyEntry[], query: string, limit: number) => __TAURI_INVOKE<FuzzyEntry[]>("fuzzy_filter_files", { files, query, limit }),
	transformImagePaths: (markdown: string, vaultPath: string | null, attachmentFolder: string | null, mode: string) => __TAURI_INVOKE<string>("transform_image_paths", { markdown, vaultPath, attachmentFolder, mode }),
	/**  Compute SHA-256 hashes for a batch of files in parallel. */
	hashFilesBatch: (vaultPath: string, paths: string[]) => typedError<string[], string>(__TAURI_INVOKE("hash_files_batch", { vaultPath, paths })),
	/**  Load and decrypt the local base manifest, returning a default if missing. */
	loadManifest: (vaultPath: string, encryptionKey: number[]) => typedError<Manifest_Serialize, string>(__TAURI_INVOKE("load_manifest", { vaultPath, encryptionKey })),
	/**  Encrypt and atomically save the base manifest to disk. */
	saveManifest: (vaultPath: string, encryptionKey: number[], manifest: Manifest_Deserialize) => typedError<null, string>(__TAURI_INVOKE("save_manifest", { vaultPath, encryptionKey, manifest })),
	/**  3-way diff: compare base, local , and remote manifests to produce sync actions. */
	computeSyncActions: (baseFiles: ManifestEntry_Deserialize[], localFiles: ManifestEntry_Deserialize[], remoteFiles: ManifestEntry_Deserialize[]) => __TAURI_INVOKE<SyncAction[]>("compute_sync_actions", { baseFiles, localFiles, remoteFiles }),
	/**  Return only entries that have a `deleted_at` timestamp. */
	collectTombstones: (files: ManifestEntry_Deserialize[]) => __TAURI_INVOKE<ManifestEntry_Serialize[]>("collect_tombstones", { files }),
	/**  Merge two tombstone lists, keeping the one with the later `deleted_at`. */
	mergeTombstones: (a: ManifestEntry_Deserialize[], b: ManifestEntry_Deserialize[]) => __TAURI_INVOKE<ManifestEntry_Serialize[]>("merge_tombstones", { a, b }),
	/**
	 *  Prune tombstones older than 90 days.
	 * 
	 *  `now_seconds` is a u32 (unix seconds) so specta can export it; widened to u64
	 *  internally to match the manifest's `deleted_at` timestamps.
	 */
	pruneTombstones: (tombstones: ManifestEntry_Deserialize[], nowSeconds: number) => __TAURI_INVOKE<ManifestEntry_Serialize[]>("prune_tombstones", { tombstones, nowSeconds }),
	/**  Read, encrypt, and upload files to S3 in a single batch. */
	syncUploadFiles: (vaultPath: string, s3Prefix: string, paths: string[], encryptionKey: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_upload_files", { vaultPath, s3Prefix, paths, encryptionKey })),
	/**
	 *  Download, decrypt, and write files from S3 in a single batch.
	 * 
	 *  `paths` and `mtimes` are parallel arrays: after each file is written its
	 *  modification time is set to `mtimes[i]` (Unix seconds) so the local mtime
	 *  matches the manifest entry and the file is not seen as locally changed on
	 *  the next sync. This folds the previously separate per-file `set_mtime` IPC
	 *  call into this single batch command.
	 * 
	 *  `mtimes` are u32 unix seconds (specta cannot export u64); each is widened to
	 *  u64 internally to match the manifest timestamps and `filetime`.
	 */
	syncDownloadFiles: (vaultPath: string, s3Prefix: string, paths: string[], mtimes: number[], encryptionKey: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_download_files", { vaultPath, s3Prefix, paths, mtimes, encryptionKey })),
	/**  Encrypt and upload the manifest to S3. */
	syncUploadManifest: (s3Prefix: string, encryptionKey: number[], manifest: Manifest_Deserialize) => typedError<null, string>(__TAURI_INVOKE("sync_upload_manifest", { s3Prefix, encryptionKey, manifest })),
	/**  Delete files from S3 by their relative paths (computes HMAC keys internally). */
	syncDeleteFiles: (s3Prefix: string, paths: string[], encryptionKey: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_delete_files", { s3Prefix, paths, encryptionKey })),
	/**
	 *  Map a relative vault path to an opaque S3 object key.
	 *  Uses HMAC-SHA256 with the encryption key to derive a deterministic 32-char
	 *  hex identifier. Same path always maps to same key — no lookup table needed.
	 */
	pathToS3Key: (relPath: string, encryptionKey: number[]) => __TAURI_INVOKE<string>("path_to_s3_key", { relPath, encryptionKey }),
	/**  Load all saved themes from the app data directory */
	loadThemes: () => typedError<ThemeData, string>(__TAURI_INVOKE("load_themes")),
	/**  Save all themes to the app data directory */
	saveThemes: (data: ThemeData) => typedError<null, string>(__TAURI_INVOKE("save_themes", { data })),
	/**  Export a single theme to a user-chosen path */
	exportTheme: (theme: Theme, dest: string) => typedError<null, string>(__TAURI_INVOKE("export_theme", { theme, dest })),
	/**  Import a theme from a user-chosen JSON file */
	importTheme: (path: string) => typedError<Theme, string>(__TAURI_INVOKE("import_theme", { path })),
};

/* Types */
export type AppSettings = {
	s3: S3Config | null,
	attachment_folder?: string | null,
	auto_sync?: boolean | null,
	conflict_strategy?: string | null,
};

export type ContentMatch = {
	path: string,
	name: string,
	line: number,
	column: number,
	context: string,
};

export type FsEntry = {
	name: string,
	is_dir: boolean,
	path: string,
	/**  Seconds since UNIX epoch (file modification time). 0 if unavailable. */
	modified: number,
};

export type FuzzyEntry = {
	name: string,
	path: string,
};

/**  Returned by `read_link_batch`. */
export type LinkEntry = {
	path: string,
	links: string[],
};

export type Manifest = Manifest_Serialize | Manifest_Deserialize;

export type ManifestEntry = ManifestEntry_Serialize | ManifestEntry_Deserialize;

export type ManifestEntry_Deserialize = {
	path: string,
	hash: string,
	modified: number,
	deleted_at: number | null,
};

export type ManifestEntry_Serialize = {
	path: string,
	hash: string,
	modified: number,
	deleted_at?: number | null,
};

export type Manifest_Deserialize = {
	version: number,
	files: ManifestEntry_Deserialize[],
};

export type Manifest_Serialize = {
	version: number,
	files: ManifestEntry_Serialize[],
};

export type S3Config = {
	endpoint: string,
	bucket: string,
	region: string,
	access_key: string,
	secret_key: string,
};

export type Snapshot = {
	/**  Filename of the snapshot (e.g. "1712928000.md") */
	filename: string,
	/**  Unix timestamp (seconds) when the snapshot was taken */
	timestamp: number,
	/**  Size of the snapshot in bytes */
	size: number,
};

export type SyncAction = {
	kind: string,
	path: string,
};

export type TagInfo = {
	tag: string,
	count: number,
	files: string[],
};

export type TextMatch = {
	from: number,
	to: number,
};

export type TextNode = {
	text: string,
	/**  ProseMirror position of the first character of this text node. */
	pos: number,
};

export type Theme = {
	name: string,
	colors: { [key in string]: string },
};

export type ThemeData = {
	themes: Theme[],
	active_theme: string | null,
};

/**  A single row in the file tree, pre-sorted and depth-annotated. */
export type TreeEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	modified: number,
	/**  Nesting depth (0 = vault root level). */
	depth: number,
};

export type VaultKeys = {
	vault_id: string,
	encryption_key: number[],
};

export type VaultProfile = {
	name: string,
	mnemonic: string,
	vault_path: string,
};

export type VaultProfiles = {
	profiles: VaultProfile[],
	last_used: string | null,
};

export type WikiLinkMatch = {
	from: number,
	to: number,
	title: string,
};

export type WorkspacePane = {
	tabs: WorkspaceTab[],
	active_tab_index: number,
};

export type WorkspaceState = {
	panes: WorkspacePane[],
	pane_flexes: (number | null)[],
	active_pane_index: number,
	expanded_folders: string[],
	sidebar_open: boolean,
	sidebar_width: number | null,
	sidebar_view: string,
	sort_order: string,
};

export type WorkspaceTab = {
	path: string,
	type: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

